# -*- coding: utf-8 -*-
"""Proyecto_clasica_r_theta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i9SriSjA9IxZce1C53HzERgOjM4I0n_1
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, PillowWriter

#-------------------------------------
#Parámetros físicos
#-------------------------------------

G = 6.674e-11           #constante de gravitación
M = 1.989e30            #masa solar [kg]

#Condiciones iniciales

#Posiciones
r1 = 1.496e11               #distancia 1 [m]
r2 = 1.496e11               #distancia 2 [m]

#Angulos de avistamiento
theta1 = 30.0               #angulo 1 [grados]
theta2 = 100.0               #angulo 2 [grados]

theta1r = np.radians(theta1) #cambio de grados a radianes
theta2r = np.radians(theta2)

#-------------------------
# cálculo de excentricidad
#-------------------------

eps = (r2 - r1)/((r1 * np.cos(theta1r)) - (r2 * np.cos(theta2r)))

#--------------------------
# Tipo de trayectoria
#--------------------------
tol=1e-3
if eps > 1 + tol:                             #si la excentricidad es mayor a 1
  print("La trayectoria es una hiperbola")    #imprimir la trayectoria es hiperbolica
  trayectoria = "hiperbolica"

if eps == 1 or np.isclose(eps, 1, atol=tol):  #si la excentricidad es igual a uno o muy cercano
  print("La trayectoria es una parábola")     #imprimir la trayectoria es parabolica
  trayectoria = "parabolica"

if eps < 1 - tol and eps > 0 + tol:           #si la excentricidad es menor a uno y mayor que cero
  print("La trayectoria es una elipse")       #imprimir la trayectoria es eliptica
  trayectoria = "eliptica"

if eps == 0 or np.isclose(eps, 0, atol=tol):    #si la excentricidad es igual a cero o muy cercano
  print("La trayectoria es una circunferencia") #imprimir la trayectoria es circular
  trayectoria = "circular"

print ("La excentricidad es ",eps, " corresponde a una trayectoria ", trayectoria)

#-------------------
#Calculo de L^2
#-------------------

L = np.sqrt(G * M * r2 * (1.0 + eps * np.cos(theta2)))

#----------------------------------------
# Dibujo de la trayectoria Hiperbólica
#----------------------------------------
if trayectoria == "hiperbolica" :
  delta2= 0.1       #ángulo pequeño que evita singualridades
  ang = np.linspace( np.arccos(-1/eps) - delta2 , -np.arccos(-1/eps) + delta2  , 100)    #vector con angulos entre arcos(-1/eps) y -arcos(-1/eps)
  angulo = np.cos(ang)                                                                   #vector con el cos de los angulos

if trayectoria  == "parabolica":
  delta1 = 0.3      #ángulo pequeño que evita singualridades
  ang = np.linspace( np.pi - delta1 , -np.pi + delta1 , 100)                             #vector con angulos entre pi-delta y -pi+delta
  angulo = np.cos(ang)                                                                   #vector con el cos de los angulos
if trayectoria ==  "circular" or trayectoria == "eliptica":
  ang = np.linspace( 0.0 , 2 * np.pi , 100)                                              #vector con todos los ángulos para otro tipo de trayectoria
  angulo = np.cos(ang)                               #vector con el cos de los ángulos
#----------------------------------------
# Calculo de la trayectoria
#----------------------------------------

tr = ((G * M / L**2) * (1.0 + eps * angulo))**-1

# Unir como columnas para obtener los datos del ángulo y trayectoria
data = np.column_stack((np.rad2deg(ang), tr))

# Guardar en archivo
np.savetxt("datos.txt", data)

# ------------------------
# Figura polar
# ------------------------
fig = plt.figure(figsize=(7,7))                 #creo la imagen
ax = fig.add_subplot(111, projection='polar')   #creo los ejes para el grafico tipo polar

# órbita completa en polar
ax.plot(ang, tr, linewidth=1.5, label="Trayectoria") #graficamos los puntos segun las columnas ang y tr

# "Sol" en el origen
ax.plot(0, 0, 'yo', markersize=12, label="Sol") #añadimos un punto en la coordenada 0,0 que representa al Sol

# punto que se moverá
planet, = ax.plot([], [], 'bo', markersize=8)

# opcional: rastro de la partícula
trail, = ax.plot([], [], 'b-', linewidth=1)

ax.legend(loc="upper right")

# ------------------------
# Inicialización
# ------------------------
def init():
    planet.set_data([], [])
    trail.set_data([], [])
    return planet, trail

# ------------------------
# Actualización
# ------------------------
def update(frame):
    planet.set_data([ang[frame]], [tr[frame]])
    trail.set_data(ang[:frame+1], tr[:frame+1])
    return planet, trail

# ------------------------
# Animación
# ------------------------
ani = FuncAnimation(
    fig,
    update,
    frames=len(ang),
    init_func=init,
    interval=20,
    blit=True
)
plt.savefig("orbita.png", dpi=300)
ani.save("orbita.gif", writer="pillow", fps=30)
plt.show()