# -*- coding: utf-8 -*-
"""Proyecto_clasica_v_r.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16CJ3q33unzctQgdKNYozX_Xs4R9e9wNV
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, PillowWriter

#------------------------------------------
#Parámetros físicos
#------------------------------------------

G = 6.674e-11           #constante de gravitación
M = 1.989e30            #masa solar [kg]

#Condiciones iniciales

v = 4.21e4                 #velocidad del cuerpo [m/s]
r = 7.48e10                #distancia de avistamiento inicial [m]
theta = np.radians(45)     #angulo de avistamiento incial

#-----------------------------------------
# Cálculo de le energía
#-----------------------------------------

E = ((0.5 * v**2) - (G * M /  r))       # calculo de E/m

print (f"{E:.2e}")                      # imprimo para verificarlo

#----------------------------------------
# Cálculo de l/m
#----------------------------------------

a =  E * r / (G * M)                  #Funcion auxiliar de precalculo
b =  np.cos(theta)                    #calculo cos(theta)

if np.isclose(a, -0.5, rtol=1e-6, atol=1e-3):  # Condición para evitar errores en órbitas circulares
 a=-0.5
 E = a * (G * M) /r
print(1 + (2 * a))
L1 =  np.sqrt(G * M * r * ( 1 + (a * b**2) + (b * np.sqrt(1 + (2 * a) + (b * a )**2 ))) ) #cálculo de l1/m
print (f"{L1:.2e}")                   #imprimo el valor de l1

L2 =  np.sqrt(G * M * r * ( 1 + (a * b**2) - (b * np.sqrt(1 + (2 * a) + (b * a )**2 ))) ) #cálculo de l2/m
print (f"{L2:.2e}")                   #imprimo el valor de l2

#---------------------------------------
# Cálculo de r
#--------------------------------------

f1 = G * M                            # cálculo de f1 prefactor
r1 = ((f1 / L1**2) * ( 1 + np.sqrt(1 + ((2 * E * L1**2)/f1**2))*b ))**-1   #cálculo de r1
print (f"{r1:.2e}")                                                        #imprimo r1

r2 = ((f1 / L2**2) * ( 1 + np.sqrt(1 + ((2 * E * L2**2)/f1**2))*b ))**-1   #cálculo de r2
print (f"{r2:.2e}")                                                        #imprimo r2

#Comparamos r1 y r2 calculados anteriormente y comparamos con r condicion inicial
#Elejimos L correcto

if np.isclose(r1, r, rtol=1e-9, atol=1e-5):       #comparo el valor de r1 calculado con r dato
  L = L1
  print("El momento correcto es", f"{L:.2e}")


if np.isclose(r2, r, rtol=1e-9, atol=1e-5):       #comparo el valor de r2 calculado con r dato
  L = L2
  print("El momento correcto es", f"{L:.2e}")

#-------------------------------------
#Cálculo de excentricidad
#------------------------------------

eps = np.sqrt(1.0 + ((2 * E * L**2)/f1**2))   #cálculo de excentricidad

#--------------------------
# Tipo de trayectoria
#--------------------------
tol=1e-3       #ingresamos un valor de tolerancia para los distintos valores de excentricidad
if eps > 1 + tol:                             #si la excentricidad es mayor a 1
  print("La trayectoria es una hiperbola")    #imprimir la trayectoria es hiperbolica
  trayectoria = "hiperbolica"

if eps == 1 or np.isclose(eps, 1, atol=tol):  #si la excentricidad es igual a uno o muy cercano
  print("La trayectoria es una parábola")     #imprimir la trayectoria es parabolica
  trayectoria = "parabolica"

if eps < 1 - tol and eps > 0 + tol:           #si la excentricidad es menor a uno y mayor que cero
  print("La trayectoria es una elipse")       #imprimir la trayectoria es eliptica
  trayectoria = "eliptica"

if eps == 0 or np.isclose(eps, 0, atol=tol):    #si la excentricidad es igual a cero o muy cercano
  print("La trayectoria es una circunferencia") #imprimir la trayectoria es circular
  trayectoria = "circular"

print ("La excentricidad es ",eps, " corresponde a una trayectoria ", trayectoria)

#----------------------------------------
# Dibujo de la trayectoria Hiperbólica
#----------------------------------------
if trayectoria == "hiperbolica" :
  delta2= 0.1       #ángulo pequeño que evita singualridades
  ang = np.linspace( np.arccos(-1/eps) - delta2 , -np.arccos(-1/eps) + delta2  , 100)    #vector con angulos entre arcos(-1/eps) y -arcos(-1/eps)
  angulo = np.cos(ang)                                                                   #vector con el cos de los angulos

#----------------------------------------
# Dibujo de la trayectoria parabolica
#----------------------------------------

if trayectoria  == "parabolica":
  delta1 = 0.3      #ángulo pequeño que evita singualridades
  ang = np.linspace( np.pi - delta1 , -np.pi + delta1 , 100)                             #vector con angulos entre pi-delta y -pi+delta
  angulo = np.cos(ang)                                                                   #vector con el cos de los angulos

#----------------------------------------
# Dibujo de la trayectoria circular o eliptica
#----------------------------------------

if trayectoria ==  "circular" or trayectoria == "eliptica":
  ang = np.linspace( 0.0 , 2 * np.pi , 100)                                              #vector con todos los ángulos para otro tipo de trayectoria
  angulo = np.cos(ang)                                                                   #vector con el cos de los angulos
#----------------------------------------
# Calculo de la trayectoria
#----------------------------------------
tr = ((f1 / L**2) * ( 1 + np.sqrt(1 + ((2 * E * L**2)/f1**2))*angulo ))**-1

# Unir como columnas para obtener los datos del angulo y trayectoria
data = np.column_stack((np.rad2deg(ang), tr))

# Guardar en archivo
np.savetxt("datos.txt", data)

# ------------------------
# Figura polar
# ------------------------
fig = plt.figure(figsize=(7,7))                   #creo la imagen
ax = fig.add_subplot(111, projection='polar')     #creo los ejes para el grafico tipo polar

# órbita completa en polar
ax.plot(ang, tr, linewidth=1.5, label="Trayectoria")    #graficamos los puntos segun las columnas ang y tr

# "Sol" en el origen
ax.plot(0, 0, 'yo', markersize=12, label="Sol")         #añadimos un punto en la coordenada 0,0 que representa al Sol

# punto que se moverá
planet, = ax.plot([], [], 'bo', markersize=8)

# opcional: rastro de la partícula
trail, = ax.plot([], [], 'b-', linewidth=1)

ax.legend(loc="upper right")

# ------------------------
# Inicialización
# ------------------------
def init():
    planet.set_data([], [])
    trail.set_data([], [])
    return planet, trail

# ------------------------
# Actualización
# ------------------------
def update(frame):
    planet.set_data([ang[frame]], [tr[frame]])
    trail.set_data(ang[:frame+1], tr[:frame+1])
    return planet, trail

# ------------------------
# Animación
# ------------------------
ani = FuncAnimation(
    fig,
    update,
    frames=len(ang),
    init_func=init,
    interval=20,
    blit=True
)
plt.savefig("orbita.png", dpi=300)
ani.save("orbita.gif", writer="pillow", fps=30)
plt.show()